# Generated by Django 4.1.7 on 2023-08-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
