# Generated by Django 4.1.7 on 2023-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_book_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, default='book-def.jpg', null=True, upload_to=''),
        ),
    ]
