# Generated by Django 4.1.7 on 2023-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_book_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, default='book_def.png', null=True, upload_to=''),
        ),
    ]
