# Generated by Django 4.1.7 on 2023-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_book_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, default='book-def.jpg', null=True, upload_to='static/images'),
        ),
    ]
